### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './dataset/DNA/root'

### ISSUE THREAD

**Issue by AndAvia** [omics-lab/VirusTaxo_Hierarchical#1]
hi，
Thanks for making such great software!I have encountered this error .This root file doesn't appear after git cloneand . I would like to get your answer!
```
python3 predict.py --input /data4/machuang/virus2/result/vOTUs.fna \
>   --model_dir ./dataset/DNA/
Traceback (most recent call last):
  File "predict.py", line 47, in <module>
    response = predict(args.input, args.model_dir)
  File "predict.py", line 25, in predict
    with open(os.path.join(model_path, current_file), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './dataset/DNA/root'
```

**Comment by AndAvia** [comment]
I did not run the model training code.
`python3 train.py \
  --data ./dataset/DNA/seq_data \
  --data_metainfo ./dataset/DNA/train.csv \
  --model_dir ./model/DNA`
